### ISSUE TITLE
API suggestions

### ISSUE THREAD

**Issue by Pyrofab** [CerulanLumina/better-graves#2]
Some mods may want to spawn custom graves, or prevent grave spawning in some circumstances. To make that easier, an event could be fired when picking the blockstate, passing in the player and the placement position.
For additional context, it would be even better to get the death blow's `DamageSource` (passed in `LivingEntity#drop`), although that would require more involved mixins (related to #1). The death blow could also be used by `DeathHandler`s when filling the gravestone.

**Comment by LuminaSapphira** [comment]
If a mod wants to spawn a custom grave, would there be multiple graves? Or a replaced grave?

**Comment by Pyrofab** [comment]
Should probably be a replaced grave, right ?

**Comment by LuminaSapphira** [comment]
That's what I was thinking. Because I'm terrible I ended up using a two-stage process for the graves, the first handles storing the inventories on death, the second actually places the graves. (Allows me to easily dodge the explosion issue).

Anyway, I've added an API method that allows for a pre-store function to be run, which tells my mod whether to use your code for storing and placement. It also accepts a function for storing, and a function for placing, which accept the player (with inventory) / mod handlers, and the world / final grave pos respectively. Let me know if there's anything else you'd need

**Comment by Pyrofab** [comment]
Note that delaying the grave placement will make everything disappear in the event that the world saves at the wrong time. You could instead maintain a list of BlockPos (graves placed this tick) and mixin to Explosion to prevent those blocks being affected.

**Comment by LuminaSapphira** [comment]
That would be a better solution, thanks~

**Comment by LuminaSapphira** [comment]
I'm going to maintain a HashSet<BlockPos> on the server thread, inserting when placing a grave, then mixin to cancel that block. The set shouldn't need to be synced or saved right?

**Comment by Pyrofab** [comment]
Ah yes, good thinking for the Set. The client is not going to destroy blocks, so no need for sync, and ticks can be considered atomic (game cannot resume in the middle of a tick), so no need for save.

**Comment by LuminaSapphira** [comment]
Cool~ Currently I'm removing the position from the set 1000ms after insertion (via the server thread executor), any ideas on how to do this better? I didn't want to remove it after explosion handling, because what if there is no explosion, for example.

**Comment by Pyrofab** [comment]
I believe there is a ServerTickCallback you could use, maybe that would work better ?

**Comment by LuminaSapphira** [comment]
I'm closing this, if there's any other API functions you or someone else might need open a new issue ^^
