### ISSUE TITLE
trinkets bug

### ISSUE THREAD

**Issue by DanShu15** [CerulanLumina/better-graves#9]
We're in MC 1.5.2 using Better Graves 0.2.1-beta.2
I'm not 100% sure where the conflict arises, but the mods involved would be Better Graves, Trinkets, Inventory Profiles, Rings of Ascension, and Banner Capes

To duplicate the issue install the mods in question (or you can come onto our server and test it if you'd like)
1-die with full armor wearing rings and a cape with a full inventory. 
2-Die again with just armor. 
3-Pick up the graves in the same order you died. 

The first grave will work as expected to restore your armor, inventory, cape, and rings but the 2nd grave will delete the rings and cape.

The problem there is if you're in a big fight and need to be equipped to get to your grave you're going to lose your trinkets when you reclaim your stuff.

Console log snippit:
https://pastebin.com/MQ9Jrb79
Player Log:
https://pastebin.com/n4XrnLh1
Server Log:
https://pastebin.com/2RyYw7Wn

**Comment by LuminaSapphira** [comment]
This should be a simple fix, but I'm not actively able to develop for Minecraft right now. If you'd like to submit a PR that would be greatly appreciated.

**Comment by LuminaSapphira** [comment]
The issue lies here: https://github.com/CerulanLumina/better-graves/blob/a3ae82edebb78a4a1d1396a4c5fa9796e2d73d1d/src/main/java/bettergraves/compat/TrinketsCompat.java#L22

The main concern is that it sets the trinkets inventory to exactly what the grave contained without first checking if there is trinkets in that slot. It should be relatively simple to add a check for the trinket inventory already containing something in that slot and if so, drop it to the player rather than attempting to fill the slot. (Or do nothing if the grave's contents were empty)

**Comment by DanShu15** [comment]
I don't actually know how to do that so I've asked in the Fabric and AOF 2 discord for assistance :) bunch of smart people there :)
I'm just a humble modpack dabbler that tweaks configs and writes datapacks lol

**Comment by haykam821** [comment]
This issue is still present on version 0.3.0 and Minecraft 1.16.1.

**Comment by LuminaSapphira** [comment]
Looks like at the time 1.16 support was merged into master there was no way to add Trinkets support into the project for 1.16, now that there is this should be fixed reasonably quickly.
